### ISSUE TITLE
Fails Perft Tests

### ISSUE THREAD

**Issue by adamtherookie** [Peregrine-Chess/peregrine-chess#5]
**Incorrect number of nodes searched**
In the starting position, the perft test outputs the wrong number of nodes after `depth=2`. The correct output can be found here: [https://www.chessprogramming.org/Perft_Results](https://www.chessprogramming.org/Perft_Results).

**To Reproduce**
1. Enter the project directory
2. Run `make && make run`
3. See error

**Expected behavior**
Output the same as the snippets here: [https://www.chessprogramming.org/Perft_Results](https://www.chessprogramming.org/Perft_Results).

**Comment by jmerono-saez** [comment]
why did you assign this to me lol

**Comment by adamtherookie** [comment]
> why did you assign this to me lol

because i still can't fix it

**Comment by argvsc47** [comment]
adulthood lv100+

**Comment by adamtherookie** [comment]
LOL

**Comment by adamtherookie** [comment]
anyway this is related to the old branch, closing
